Output demos/lose.gif
Set Width 2500
Set Height 1200
Sleep 500ms
Type "./fac"
Tab
Enter
Sleep 6s
Type "1"
Enter
Sleep 500ms
Type "1"
Enter
Type "3"
Sleep 500ms
Type "9"
Backspace
Type "0"
Enter
Sleep 500ms
Type "1"
Enter
Sleep 500ms
Type "0"
Enter
Sleep 500ms
Type "14"
Enter
Sleep 500ms
Type "1"
Enter
Sleep 2s
Type "0"
Enter
Sleep 11.5s
Type "1"
Enter
Sleep 1.5s
Type "0"
Enter
Sleep 500ms
Type "1"
Enter
Sleep 500ms
Type "0"
Enter
Sleep 11.5s
Type "exit"
Sleep 1.5s
